Repository theforeman/puppet-dhcp, pull requests merged in 2018-07, with the labels that each got.

#128 msync: Acceptance tests update
  .sync.yml
  .travis.yml
  Gemfile
  spec/acceptance/nodesets/docker/centos-6.yml
  spec/acceptance/nodesets/docker/centos-7.yml
  spec/acceptance/nodesets/docker/debian-8.yml
  spec/acceptance/nodesets/docker/debian-9.yml
  spec/acceptance/nodesets/docker/ubuntu-14.04.yml
  spec/acceptance/nodesets/docker/ubuntu-16.04.yml
Labels: Modulesync, Needs testing, Not yet reviewed

#129 msync: rake changelog & beaker hostname
  .travis.yml
  Gemfile
  Rakefile
Labels: Needs testing, Not yet reviewed

#131 Fixes GH-130 - bump compatible version of camptocamp-systemd module
  metadata.json
Labels: Needs testing

#132 msync: changelog user & custom facts in tests
  Rakefile
  spec/spec_helper.rb
Labels: Needs testing, Not yet reviewed
