Repository theforeman/puppet-dhcp, pull requests merged in 2020-05, with the labels that each got.

#174 Modulesync: Require voxpupuli-test 1.4
  Gemfile
  Rakefile
  spec/spec_helper_acceptance.rb
Labels: Needs testing, Not yet reviewed

#167 Fixes #29189 - support el8
  .sync.yml
  .travis.yml
  manifests/params.pp
  metadata.json
Labels: Needs testing

#176 Release 6.0.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing, Waiting on contributor, skip-changelog
