Repository theforeman/puppet-dhcp, pull requests merged in 2020-09, with the labels that each got.

#177 Adjust config directory mode to the system defaults
  manifests/init.pp
  manifests/params.pp
Labels: Enhancement, Needs testing

#178 Fix default conf_dir mode for Debian
  manifests/params.pp
Labels: Needs testing

#179 Release 6.1.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing, skip-changelog
