Repository theforeman/puppet-dhcp, pull requests merged in 2021-07, with the labels that each got.

#192 Bump version to 7.0.0
  metadata.json
Labels: Needs testing, skip-changelog

#191 Drop Puppet 5 support
  metadata.json
Labels: Needs testing

#193 fix dhcp::host comment param
  spec/defines/host_spec.rb
  templates/dhcpd.host.erb
Labels: Bug, Needs testing, Not yet reviewed

#194 Release 7.0.0
  CHANGELOG.md
Labels: Needs testing, skip-changelog
