Repository theforeman/puppet-dhcp, pull requests merged in 2022-01, with the labels that each got.

#207 Pin rdoc to < 6.4
  Gemfile
Labels: Needs testing, Not yet reviewed, skip-changelog

#208 Add Debian 11 and Ubuntu 20.04 support
  metadata.json
Labels: Enhancement, Needs testing

#206 add support for raw configuration for host declarations.
  manifests/host.pp
  spec/defines/host_spec.rb
  templates/dhcpd.host.erb
Labels: Needs testing
