Repository theforeman/puppet-dhcp, pull requests merged in 2023-11, with the labels that each got.

#227 Mark compatible with puppet/systemd 5.x & 6.x
  metadata.json
Labels: Enhancement

#225 Update gems to support testing Puppet 8
  .github/workflows/ci.yml
  .gitignore
  CONTRIBUTING.md
  Gemfile
  spec/spec_helper_acceptance.rb
Labels: Not yet reviewed, Modulesync

#226 allow stdlib 9.x
  metadata.json
Labels: Enhancement

#228 Release 9.1.0
  CHANGELOG.md
  metadata.json
Labels: skip-changelog
